name: Playwright Tests
on: 
  push: 
    branches: 
      - main

jobs:
  playwrighttests:
    runs-on: ubuntu-latest
    container: 
      image: mcr.microsoft.com/playwright:v1.45.1-focal
      env:
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm ci

      - name: Start the shopping store app
        run: |
          chmod +x ./shopping-store-linux-arm64
          ./shopping-store-linux-arm64 &
          # Give the server a moment to start
          sleep 10

      - name: Verify server is running
        run: |
          curl -I http://localhost:2221/ || exit 1

      - name: Run tests
        run: |
          npm run test:ci
