name: Playwright Tests
on: 
  push: 
    branches: [ main ]
jobs:
  playwrighttests:
    runs-on: ubuntu-latest
    container: 
        image: mcr.microsoft.com/playwright:v1.45.1-focal
        env:
            ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run tests
        run: | 
            echo "Start the shopping store app"
            chmod +x ./shopping-store-linux-arm64 &
            echo "Install dependencies"
            npm ci
            echo "Run playwright tests"
            npm test
